# We need to provide ip,port,databasename as a key value pair
#localhost = 127.0.0.1 we can mention this also, or in office we need to mention database ip
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#If journaldb not present then it will be created
#spring.data.mongodb.database=journaldb
#as of now there is no authentication added if it is added we need to mention username password like this
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

spring.data.mongodb.uri=mongodb://localhost:27017/journaldb

